title: About Me
email: nicolai@drengene.dk
description: I love technology and I love enabling people. I love going broad and I love going deep.
github_username:  gahms

theme: minima
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/gahms" }
    - { platform: twitter, user_url: "https://twitter.com/nicolaih" }
